### ISSUE TITLE
Checkvist?

### ISSUE THREAD

**Issue by bmann** [rtanglao/rtDOTcom#13]
How did you find it? Why checkvist?

**Comment by rtanglao** [comment]
because it's a cross platform outliner that works on mac, windows, ios and linux :-) (if omnioutliner had a web app i'd probably switch back), i found it via an 1990s old school knowledge management forum that i stopped subscribing to because it was very noisy (need to resubscribe to it using another aggregator like fraidycat)

**Comment by rtanglao** [comment]
found the old skool forum:
* https://www.outlinersoftware.com/
* which i of course blogged about and forgot :-) http://rolandtanglao.com/2019/05/13/p1-outlinersoftware-old-skool-forum-for-outliners-pims-knowledge-management/
