### ISSUE TITLE
Flickr @ 20

### ISSUE THREAD

**Issue by cogdog** [rtanglao/rtDOTcom#18]
Re: http://rolandtanglao.com/2024/02/29/p1-happy-20th-birthday-flickr/

500k photos, you are a champ. I calculate it will take me 140 years to catch up.

There is a reference to "Boris's post" above his quote but alas, no link.

I'm envious you and that dinner group were there from the start. I am not sure what is "the community" you speak of that left. It's still there, just not evenly distributed.

And I am letting our [bet](https://pechaflickr.net/bet/) acrrue interest, you will have to feed me lunch for a long time.

**Comment by rtanglao** [comment]
* I updated the post @cogdog with the text `(the community is a long tail of micro communities with no real coordination function at any level but maybe that's the internet today a bunch of sub-cultures i.e. Switzerland instead of Canada :-) ?!?!)` but having issues uploading it to my surge.sh

**Comment by rtanglao** [comment]
* looks like the problem with my website was fixed: `the issue is fixed after rollback was made to the network layer that handles the communication from our deployment servers and our edge nodes. The issue is related to either a timeout mechanism that was added or its a payload size issue`
so closing
